<!-- 
  ARQUIVO: CallbackApi.csproj
  UTILIDADE: Define as configurações do projeto, versão do .NET, bibliotecas (NuGet) 
  e como a aplicação deve ser compilada.
-->
<!-- Arquivo de projeto que define como a aplicação deve ser compilada e quais bibliotecas usa. -->
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Define a versão do .NET utilizada (neste caso, .NET 10). -->
    <TargetFramework>net9.0</TargetFramework>
    <!-- Ativa verificações para evitar erros de referência nula. -->
    <Nullable>enable</Nullable>
    <!-- Permite usar bibliotecas comuns sem precisar de muitos "using" no topo dos arquivos. -->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Bibliotecas externas instaladas via NuGet (Swashbuckle é para o Swagger). -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
  </ItemGroup>

</Project>
