[database]
host = {{ default "postgres" (env "POSTGRES_HOST") }}
port = {{ default "5432" (env "POSTGRES_PORT") }}
database = {{ default "postgres" (env "POSTGRES_DB") }}
user = {{ default "postgres" (env "POSTGRES_USER") }}
password = {{ env "POSTGRES_PASSWORD" }}
sslmode = {{ default "disable" (env "POSTGRES_SSLMODE") }}
